### ISSUE TITLE
Failed to prepare camera

### ISSUE THREAD

**Issue by frog1014** [ekimual/croperino#14]
I get this error in Samsung s7(6.0, 7.0) and HTC m7(5.0)
but works in SONY m4(5.0), Nexus 6(6.0)

`E/Croperino: Failed to prepare camera: 
                                                                     java.io.IOException: No such file or directory
                                                                         at java.io.UnixFileSystem.createFileExclusively0(Native Method)
                                                                         at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)
                                                                         at java.io.File.createNewFile(File.java:948)
                                                                         at java.io.File.createTempFile(File.java:1862)
                                                                         at com.mikelau.croperino.CroperinoFileUtil.newCameraFile(CroperinoFileUtil.java:60)
                                                                         at com.mikelau.croperino.Croperino.prepareCamera(Croperino.java:72)
                                                                         at com.demo.sercomm.mwc2017.MainActivity$3.onClick(MainActivity.java:256)
                                                                         at android.view.View.performClick(View.java:6207)
                                                                         at android.view.View$PerformClick.run(View.java:23639)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6688)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)`

**Comment by ekimual** [comment]
@frog1014 Hi can you try this again for version 1.1.0, sorry I don't have the said device to reproduce it so I just rely on remote debugging for these kind of issues.

**Comment by frog1014** [comment]
camera works!
but there is error in cropImage .

D/MainActivity: onActivityResult() called with: requestCode = [1], resultCode = [-1], data = [null]

03-01 11:07:32.728 31022-31022  E/CropImage: file /sdcard/GaiaMWC2017/imgs not found


Btw, after my last post,I have code this and works perfect with 1.0.9 on 5.0~7.0

```
final File externalStoragePublicDirectory = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DCIM);
        File storageDir = new File(externalStoragePublicDirectory + File.separator + "Camera");
        File mwcdemoDir = new File(externalStoragePublicDirectory + File.separator + "MWCDEMO");
        try {
            storageDir.mkdir();
            mwcdemoDir.mkdir();
            imgPath = mwcdemoDir.getAbsolutePath();
            rawImgPath = mwcdemoDir.getCanonicalPath();
            new CroperinoConfig(imgName, imgPath, rawImgPath);
            CroperinoFileUtil.verifyStoragePermissions(MainActivity.this);
            CroperinoFileUtil.setupDirectory(MainActivity.this);
        } catch (IOException e) {
            e.printStackTrace();
        }
```
